# make the right side central
CONFIG_ZMK_KEYBOARD_NAME="swweeep"
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y

# enable pointing
CONFIG_ZMK_POINTING=y

# TP start up delay
CONFIG_ZMK_INPUT_MOUSE_PS2_POWER_ON_RESET_TIME=2000