# make the right side central
CONFIG_ZMK_KEYBOARD_NAME="swweeep"
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y

# enable pointing
CONFIG_ZMK_POINTING=y

# logging delay
CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=8000